config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  devise_for :users
  root to: "products#index"
  # match '*path' => redirect("products#index"), via: [:get]

  # get '/sale_transactions',
  #     to: 'sale_transactions#index',
  #     constraints: ->(request){  User.current_user.present? && User.current_user.access_right_enum == 1}
  
  #resources
  resources :carts, :path => "my_cart"
  resources :users
  resources :sale_transactions, :path => "my_transactions"
  resources :sale_transaction_line_items
  resources :products
  resources :product_parts
  resources :hotels
end

app/views/shared/_flash_message.html.erb
<% if flash.any? %>
    <script type="text/javascript">
        <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
            toastr.<%= type %>('<%= value %>', '', {
                // "positionClass": "toast-top-left"
            })
        <% end %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
  <% if current_user.present? && current_user.has_access_to_side_bar(request.path.to_s) %>
    <div id="main">
      <a class="navbar- " style="font-family:'Courier New'; font-size: 40px;" id="openbtn" onclick="openNav()"><span style="font-size: 30px;padding-right: 3%;">&#9776;</span>Depot</a>
    </div>
  <% else %>
    <a class="navbar-brand" style="font-family:'Courier New'; font-size: 40px;" >Depot</a>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

      <li class="nav-item" style="font-size: 20px;">
        <%= link_to (root_path),  method: :get, class: 'nav-link' do %>
          <%= fa_icon "home" %> Home
        <% end %>
      </li>
      
      <% if user_signed_in? %>
        <% if current_user.access_right_enum == 1 %>
          <li class="nav-item" style="font-size: 20px;">
            <%= link_to (carts_url), method: :get, class: 'nav-link' do %>
              <%= fa_icon "shopping-cart" %> My Cart
            <% end %>
          </li>
          <li class="nav-item" style="font-size: 20px;">
            <%= link_to (sale_transactions_url),  method: :get, class: 'nav-link' do %>
              <%= fa_icon "list" %> My Transactions
            <% end %>
          </li>
        <% else %>
          <li class="nav-item" style="font-size: 20px;">
            <%= link_to (product_parts_url),  method: :get, class: 'nav-link' do %>
              <%= fa_icon "wrench" %> Product Parts
            <% end %>
          </li>
        <% end %>
        <li class="nav-item" style="font-size: 20px;">
          <%= link_to (user_url(current_user)), method: :get, class: 'nav-link' do %>
            <%= fa_icon "user" %> Profile
          <% end %>
        </li>
        <li class="nav-item" style="font-size: 20px;">
          <%= link_to (destroy_user_session_path), method: :delete, class: 'nav-link' do %>
            <%= fa_icon "sign-out" %> Sign Out
          <% end %>
        </li>
      <% else %>
        <li class="nav-item" style="font-size: 20px;">
          <%= link_to (new_user_registration_path), class: 'nav-link' do %>
            <%= fa_icon "user-o" %> Register
          <% end %>
        </li>
        <li class="nav-item" style="font-size: 20px;">
          <%= link_to (new_user_session_path), class: 'nav-link' do %>
            <%= fa_icon "sign-in" %> Sign in
          <% end %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <h1 class="display-4 sidebar-title" style="text-align:center" >Menu</h1>
  <div style="border-bottom: 1px dotted black;"></div>
  <br />
  <% if page.eql? "products" %>
    <%= link_to (new_product_path), remote: true, class: "btn btn-sidebar" do %>
        <%= fa_icon "plus" %> Create New Product
    <% end %>
  <% else %>
    <%= link_to (new_product_part_path), remote: true, class: "btn btn-sidebar" do %>
        <%= fa_icon "wrench" %> Create New Part
    <% end %>
  <% end %>
</div>