config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  devise_for :users
  root to: "products#index"
  # match '*path' => redirect("products#index"), via: [:get]

  # get '/sale_transactions',
  #     to: 'sale_transactions#index',
  #     constraints: ->(request){  User.current_user.present? && User.current_user.access_right_enum == 1}
  
  #resources
  resources :carts, :path => "my_cart"
  resources :users
  resources :sale_transactions, :path => "my_transactions"
  resources :sale_transaction_line_items
  resources :products
  resources :product_parts
  resources :hotels
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :sale_transaction_line_items
    belongs_to :user
    validates :user_id, presence: true

    cattr_accessor :current_cart

    def add_product(product)
        current_item = sale_transaction_line_items.where("product_id = #{product.id} and is_sold = false")[0]
        if current_item.present?
            current_item[:quantity] += 1
            current_item[:subtotal] += product[:unit_price]
        else
            current_item = sale_transaction_line_items.build(product_id: product.id)
            current_item[:subtotal] = product[:unit_price]
        end
        current_item
    end

    def remove_product(product)
        current_item = sale_transaction_line_items.find_by(product_id: product.id)
        current_item.quantity -= 1;
        current_item[:subtotal] -= product[:unit_price]
        current_item
    end

    def total_price
        sale_transaction_line_items.where(:is_sold => false).to_a.sum { |item| item.total_price }
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ index destroy ]
  before_action only: [:index, :destroy] do 
    self.check_access(User.access_rights[:customer])
  end
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    @sale_transaction_line_items = Cart.current_cart.sale_transaction_line_items.where(:is_sold => false)
  end

  def destroy
    @cart.sale_transaction_line_items.where(:is_sold => false).delete_all

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Your cart is currently empty' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.current_cart
    end

    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      redirect_to root_path, notice: 'Invalid cart'
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/destroy.js.erb
$('#cart').remove();
$('#cartButtons').remove();
$('#total-price').html("Cart Total: <%= number_to_currency(0.00) %>");

app/views/carts/index.html.erb
<br/>

<h3 style="text-align:center;padding-bottom: 2%;">My Cart</h3>

<div class="container">
  <div class="row">
    <div class="col align-self-center">
      <div id="cart" style="display: flex !important; flex-direction: row !important; flex-flow: wrap">
          <%= render @sale_transaction_line_items %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col align-self-center">
      <div style="display:flex; flex-direction:column; align-items:center;padding-top: 5%;">
        <p id="total-price" style="font-size: 20px;">
          <%= fa_icon "shopping-cart" %>&nbsp; Cart Total: <%= number_to_currency(@cart.total_price) %>
        </p>
        <div id="cartButtons" style="display:flex; flex-direction:row; align-items:center; padding-top: 10px;">
          <% if @sale_transaction_line_items.present? %>
            <%= button_to 'Empty cart', "/my_cart/#{@cart.id}", method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> &nbsp;&nbsp;
            <%= button_to "Check out", sale_transactions_path, method: :post, class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>