config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  devise_for :users
  root to: "products#index"
  # match '*path' => redirect("products#index"), via: [:get]

  # get '/sale_transactions',
  #     to: 'sale_transactions#index',
  #     constraints: ->(request){  User.current_user.present? && User.current_user.access_right_enum == 1}
  
  #resources
  resources :carts, :path => "my_cart"
  resources :users
  resources :sale_transactions, :path => "my_transactions"
  resources :sale_transaction_line_items
  resources :products
  resources :product_parts
  resources :hotels
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :products_staffs, class_name: "ProductsStaffs"
    has_many :users, through: :products_staffs
    has_many_attached :images
    has_many :product_parts
    accepts_nested_attributes_for :product_parts, allow_destroy: true, reject_if: :all_blank
    
    validates :name, :description, :unit_price, :category, :model, :delivery, presence: true
    validates :unit_price, numericality: {greater_than_or_equal_to: 0.01}
    validate  :acceptable_images

    def is_product_referenced_by_line_items
        if SaleTransactionLineItem.find_by_product_id(self.id).nil?
            return false
        end 
        return true
    end

    def acceptable_images
        if images.count <= 0
            errors.add(:images, "Upload at least one image")
        end
    end 

    def thumbnail(image)
        return image.variant(resize: '300x200!').processed
    end

    def show_image(image)
        return image.variant(resize: '600x300!').processed
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ update destroy ]
  before_action only: [:create, :edit, :update, :destroy, :new] do 
    self.check_access(User.access_rights[:manager])
  end

  # GET /products or /products.json
  def index
    @products = Product.where(is_deleted: false)
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.includes(:product_parts).find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.includes(:product_parts).find(params[:id])
  end

  # POST /products or /products.json
  def create
      @product = Product.new(product_params)
      @product.category = params[:category].reduce("") { |text, category| text + " " + category}
      respond_to do |format|
        if @product.save
          create_log(@product, "create")
          format.html { redirect_to root_path, notice: "Product was successfully created." }
          format.js
          format.json { render :show, status: :created, location: @product }
        else
          format.js { render :new } # to show form validation errors
          format.html { redirect_to products_url, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        create_log(@product, "update")
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.js
        format.json { render :show, status: :ok, location: @product }
      else
        format.js { render :new } # to show form validation errors
        format.html { redirect_to products_url, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    if @product.is_product_referenced_by_line_items
      flash[:error] = "Product is in use!"

      respond_to do |format|
        format.html { redirect_to products_url}
        format.json { head :no_content }
      end
      
      return
    else 
      @product.update(is_deleted: true)
      create_log(@product, "delete")     

      respond_to do |format|
        format.html { redirect_to root_path, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:product_id, 
                                      :name, 
                                      :description, 
                                      :unit_price, 
                                      :model, 
                                      :delivery, 
                                      images: [], 
                                      category: [],
                                      product_parts_attributes: [:id, :name, :date_expired, :_destroy, :description]
                                    )
    end

    def create_log(product, operation)
        log = ProductsStaffs.new
        log.product= product
        log.user = current_user
        log[:log_time] = Date.today
        log[:operation] = operation
        log.save!
    end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :remote => true do |f| %>

  <% if @product.errors.any? %>
    <% p@roduct.errors.each do |error| %>
      <div class="alert alert-danger" role="alert">
        <%= error.full_message %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, required: true, class: "form-control", placeholder: "Product name"%>
  </div>

  <div class="form-group">
    <%= f.label :model %><br/>
    <%= f.text_field  :model, required: true, class: "form-control", placeholder: "Model name"%>
  </div>

  <div class="form-group">
    <%= f.label :delivery %><br/>
    <%= f.text_field  :delivery, required: true, class: "form-control", placeholder: "Delivery address"%>
  </div>

  <div class="form-group">
    <%= f.label :description %><br/>
    <%= f.text_area :description, required: true, class: "form-control", placeholder: "Product description"%>
  </div>

  <div class="form-group">
    <%= f.label :unit_price %><br/>
    <%= f.number_field  :unit_price, required: true, in: 1.0..10000.0, class: "form-control", placeholder: "Product price"%>
  </div>

  <div class="form-group">
    <%= f.label :category %><br/>
    <select name="category[]" multiple="multiple" style="width:100%">
      <option value="Gameboy">Gameboy</option>
      <option value="T-shirt">T-shirt</option>
      <option value="Jewellery">Jewellery</option>
      <option value="Jeans">Jeans</option>
    </select>
    <small class="form-text text-muted">Select at least one.</small>
  </div>

  <div class="form-group">
    <%= f.label :images %><br/>
    <%= f.file_field :images, multiple: true, class: "form-control-file"%>
  </div>

  <div id="nested-portion">
    <p class="lead">Product Parts:</p>
    <div>
      <%= f.fields_for :product_parts do |product_part| %>
        <%= render 'product_part_fields', f: product_part %>
      <% end %>
    </div>

    <div class="btn btn-outline-primary btn-sm">
      <%= link_to_add_association 'Add Product Part', f, :product_parts, style: "text-decoration: none"%>
    </div>
  </div>

  <br/>
  <br/>
  
  <div class="col text-center">
    <%= f.submit class: "btn btn-primary mb-2"%>
  </div>

<% end %>

<script>
  $('#nested-portion').on('cocoon:after-insert', function(e, insertedItem) {
      insertedItem.find('.datetimepicker').datetimepicker({
      uiLibrary: 'bootstrap4',
      modal: true,
      footer: true,
      format: 'dd/mm/yyyy HH:MM'
    });
  });

  $('.datetimepicker').datetimepicker({
    uiLibrary: 'bootstrap4',
    modal: true,
    footer: true,
    format: 'dd/mm/yyyy HH:MM'
  });
</script>

app/views/products/_product.html.erb
<div style="padding: 0px 10px;">
    <div class="card text-center" style="width: 20rem;">
        <div class="card-img-top">
            <% if product.images.first.present? %>
                <%= image_tag product.thumbnail(product.images.first), class: "card-img-top" %>
            <% else %>
                <img class="card-img-top" src="https://picsum.photos/300/200" alt="Card image cap">
            <% end %>
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text"><%= number_to_currency(number_with_delimiter(product.unit_price, delimiter: ",")) %></p>
            <%= link_to 'View details', product, method: :get, class: 'btn btn-primary' %>
        </div>
    </div>
    <br />
</div>

app/views/products/_product_detail.html.erb
<h1 class="display-4 text-muted" style="color: #444444 !important;"><%= product_detail.name %></h1>
<br/>
<p class="text-muted text-uppercase medium"><%= fa_icon "tags", style: "font-size: 30px;" %> <span style="font-size: 20px;"><%= product_detail.category %></span></p>
<div id="carouselImages" class="carousel slide" data-ride="carousel">
<div class="carousel-inner">
    <div class="carousel-item active">
        <%= image_tag product_detail.show_image(product_detail.images.first), class: "d-block w-100" %>
        <div class="carousel-caption d-none d-md-block">
        <%= link_to rails_blob_path(product_detail.images.first, disposition: 'attachment') do %>
            <%= fa_icon "download", style: "font-size: 20px; padding: 5px 5px;background-color: white; color: blue; border-radius: 50%;" %>
        <% end %>
        </div>
    </div>
    <% (1...product_detail.images.count).each do |image|  %>
    <div class="carousel-item text-center">
        <%= image_tag product_detail.show_image(product_detail.images[image]), class: "d-block w-100" %>
        <div class="carousel-caption d-none d-md-block">
            <%= link_to rails_blob_path(product_detail.images[image], disposition: 'attachment') do %>
            <%= fa_icon "download", style: "font-size: 20px; padding: 5px 5px;background-color: white; color: blue; border-radius: 50%;" %>
            <% end %>
        </div>
    </div>
    <% end %>
</div>
<% if product_detail.images.count > 1 %>
    <a class="carousel-control-prev" href="#carouselImages" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselImages" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
    </a>
<% end %>
</div>
<br/>
<div class="lead" style="color: gray; width: 30rem;"><%= fa_icon "info" %> &nbsp; <%= product_detail.description %></div>
<br/>
<div class="table-responsive">
<table class="table borderless table-sm">
    <tbody>
    <tr>
        <th class="text-muted" scope="row"><strong>Model</strong></th>
        <td class="text-muted"><%= product_detail.model %></td>
    </tr>
    <tr>
        <th class="text-muted" scope="row"><strong>Delivery</strong></th>
        <td class="text-muted"><%= product_detail.delivery %></td>
    </tr>
    <tr>
        <th class="text-muted" scope="row"><strong>Included Parts</strong></th>
        <td class="text-muted">
            <% (0...(product_detail.product_parts.count - 1)).each do | index | %>
                <span class="product-detail-part-button" onclick="redirectToPartDetails(<%= product_detail.product_parts[index].id %>)">
                    <%= product_detail.product_parts[index].name %>
                </span>,  
            <% end %>
            <span class="product-detail-part-button" onclick="redirectToPartDetails(<%= product_detail.product_parts[product_detail.product_parts.count - 1].id %>)">
                <%= product_detail.product_parts[product_detail.product_parts.count - 1].name %>
            </span>
        </td>
    </tr>
    </tbody>
</table>
</div>
<div style="border-bottom: 1px solid gray;"></div>
<br/>
<div class="text-center">
<% if user_signed_in? == true && current_user.access_right_enum == 2 %>
    <%= link_to (edit_product_path(product_detail)), remote: true, class: 'btn btn-primary', style: "color: white" do %>
    <%= fa_icon "pencil" %> Edit Product
    <% end %>
    &nbsp;
    <%= link_to (product_detail), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary', style: "color: white" do %>
    <%= fa_icon "trash" %> Delete Product
    <% end %>
<% else %>
    <%= link_to (sale_transaction_line_items_path(product_id: product_detail)), method: :post, class: 'btn btn-primary', style: "color: white" do %>
    <%= fa_icon "shopping-cart" %> Add To Cart
    <% end %>
<% end %>
</div>

<script type="text/javascript">
  function redirectToPartDetails(id) {
    window.location.href = "http://localhost:3000/product_parts/" + id;
  }
</script>

app/views/products/_product_part_fields.html.erb
<div class="nested-fields">
    <div class="form-group">
        <%= f.label :name %><br/>
        <%= f.text_field :name, required: true, class: "form-control", placeholder: "Product part name"%>
    </div>

    <div class="form-group">
        <%= f.label :description %><br/>
        <%= f.text_field :description, required: true, class: "form-control", placeholder: "Product part description"%>
    </div>

    <div class="form-group ">
        <%= f.label :date_expired %><br/>
        <%= f.text_field :date_expired, required: true, class: "form-control", placeholder: "Expiry date", class: "datetimepicker" %>
    </div>

    <%= link_to_remove_association 'Remove Part', f %>
    
</div>
<br/>

app/views/products/create.js.erb
$('#modalProduct').modal("hide");
$('#products').append("<%=j render @product %>")

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<span style="margin-left:50%">
    <%= link_to 'Back', products_path %>
</span>

app/views/products/edit.js.erb
$('#modalBody').html("<%=j render 'form', product: @product %>")
$('#modalProduct').modal("show");
$('select').select2({
    tags: true,
    tokenSeparators: [',', ' ']
});

app/views/products/index.html.erb
<br/>

<h1 class="display-4" style="text-align:center" >View All Products</h1>
<%= render partial: "shared/sidebar", locals: { page: "products" } %>

<br/>

<div class="container">
  <div id="products" style="display: flex !important; flex-direction: row !important; flex-flow: wrap">
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalProduct" tabindex="-1" role="dialog" aria-labelledby="modalProductTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Create New Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modalBody" class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/new.js.erb
$('#modalBody').html("<%=j render 'form', product: @product %>")
$('#modalProduct').modal("show");
$('select').select2({
    tags: true,
    tokenSeparators: [',', ' ']
});

app/views/products/show.html.erb
<br/>

<div class="container">
  <div class="row">
    <div class="col" id="product_detail_wrapper">
      <%= render partial: 'products/product_detail', locals: { product_detail: @product } %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalProduct" tabindex="-1" role="dialog" aria-labelledby="modalProductTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Product Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modalBody" class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/products/update.js.erb
$('#modalProduct').modal("hide");
$('#product_detail_wrapper').html("<%=j render partial: 'products/product_detail', locals: { product_detail: @product } %>")